name: Federico Hamann Artist
favicon: null
layout_spectrum: 0.9596089215483516
typography_spectrum: 0.6706200412008911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#137cca'
    - '#f0f1eb'
    - '#fd9a90'
    - '#233946'
    - '#dc5963'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
